from django.contrib import admin
from .models import(staff,bus,booking,karnataka,Punjab,Andra,TamilNadu,Kerala,user)
admin.site.register(staff)
admin.site.register(bus)
admin.site.register(booking)
#admin.site.register(user)
admin.site.register(karnataka)
admin.site.register(Punjab)
admin.site.register(Andra)
admin.site.register(TamilNadu)
admin.site.register(Kerala)
admin.site.register(user)
